language: java
jdk:
  - oraclejdk8
after_success:
  - chmod +x ./scripts/hello_world.sh
  - chmod +x ./scripts/echo_file.sh
  - ./scripts/hello_world.sh
  - ./scripts/echo_file.sh ./docs/dummyFile.txt
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
